# Generated by Django 3.0.6 on 2020-09-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0004_userprofile_username'),
        ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skills_choice',
            field=models.CharField(
                choices=[('FI', 'First'), ('SE', 'Second'), ('TH', 'Third')],
                default='First, Second, Third', max_length=100),
            preserve_default=False,
            ),
        ]
