# Generated by Django 3.0.6 on 2020-09-28 23:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0005_skills_skills_choice'),
        ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skills_choice',
            ),
        ]
