# Generated by Django 3.0.6 on 2020-10-30 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0006_remove_skills_skills_choice'),
        ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='created_by',
            field=models.ForeignKey(default='',
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL, unique=True),
            ),
        ]
