# Generated by Django 3.0.11 on 2021-01-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20210120_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(related_name='profile_skills', to='profiles.Skills'),
        ),
    ]
