# Generated by Django 3.2 on 2021-05-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0013_auto_20210130_0841'),
        ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True,
                                         related_name='profile_skills',
                                         to='profiles.Skills'),
            ),
        ]
