# Generated by Django 3.2 on 2021-05-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0014_alter_userprofile_skills'),
        ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
            ),
        ]
