# Generated by Django 5.2.5 on 2025-08-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
