# Generated by Django 3.0.11 on 2021-04-10 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ]

    operations = [
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('title',
                 models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField()),
                ('timeline',
                 models.CharField(blank=True, default='', max_length=50)),
                ('requirements',
                 models.CharField(blank=True, default='', max_length=50)),
                ('created_by', models.OneToOneField(default='',
                                                    on_delete=django.db.models.deletion.CASCADE,
                                                    to=settings.AUTH_USER_MODEL)),
                ],
            ),
        ]
