# Generated by Django 3.0.11 on 2021-04-18 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_applicant_position'),
        ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='name',
            ),
        migrations.AddField(
            model_name='applicant',
            name='applicant',
            field=models.ForeignKey(default='',
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
            preserve_default=False,
            ),
        ]
