# Generated by Django 3.0.11 on 2021-04-28 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_auto_20210418_0712'),
        ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='created_by',
            field=models.ForeignKey(default='',
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
            ),
        ]
