# Generated by Django 3.0.11 on 2021-04-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0004_auto_20210428_0153'),
        ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='Status',
            ),
        migrations.AddField(
            model_name='applicant',
            name='hired',
            field=models.BooleanField(default=False),
            ),
        migrations.AddField(
            model_name='position',
            name='filled',
            field=models.BooleanField(default=False),
            ),
        ]
