# Generated by Django 3.2 on 2021-05-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210428_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='hired',
            field=models.BooleanField(),
        ),
    ]
