# Generated by Django 3.2 on 2021-05-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_applicant_hired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='hired',
            field=models.BooleanField(default=False),
        ),
    ]
