# Generated by Django 3.2 on 2021-05-28 04:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0008_alter_applicant_hired'),
        ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering':('title',)},
            ),
        ]
