# Generated by Django 3.2 on 2021-05-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0009_alter_position_options'),
        ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='hired',
            field=models.BooleanField(),
            ),
        ]
