# Generated by Django 3.0.6 on 2020-07-01 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
        ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
            ),
        ]
